trigger:
- main

pool: MyPool

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: 'kavysampleapp'
  containerRegistry: 'kavyacr27'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: package
  displayName: Build and Package
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'SampleApp'
        publishLocation: 'Container'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: $(containerRegistry)
        command: 'buildAndPush'
        repository: $(imageRepository)
        Dockerfile: $(dockerfilePath)
        buildContext: '$(Build.ArtifactStagingDirectory)'
        tags: |
          $(tag)
